
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- stage

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Starter pipeline
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.14.5'

- task: TerraformTaskV1@0
  displayName: 'Terraform Init'
  inputs:
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'usbank_service_connection_tf'
    backendAWSBucketName: 'usbank-bucket'
    backendAWSKey: 'terraform.tfstate'

- task: TerraformTaskV1@0
  displayName: 'Terraform Plan'
  inputs:
    provider: 'aws'
    command: 'plan'
    environmentServiceNameAWS: 'usbank_service_connection_tf'